// Highlighted sidebar items
export const NEW = ['Target Cursor', 'Ripple Grid', 'Magic Bento', 'Galaxy', 'Text Type', 'Glass Surface', 'Sticker Peel', 'Scroll Stack', 'Faulty Terminal', 'Pill Nav', 'Card Nav', 'Logo Loop', 'Electric Border'];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Text Animations',
    subcategories: [
      'Split Text',
      'Blur Text',
      'Circular Text',
      'Shiny Text',
      'Text Pressure',
      'Curved Loop',
      'Fuzzy Text',
      'Gradient Text',
      'Text Trail',
      'Falling Text',
      'Text Cursor',
      'Decrypted Text',
      'Ascii Text',
      'Scramble Text',
      'True Focus',
      'Scroll Float',
      'Scroll Reveal',
      'Rotating Text',
      'Glitch Text',
      'Scroll Velocity',
      'Text Type',
      'Variable Proximity',
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Fade Content',
      'Noise',
      'Splash Cursor',
      'Logo Loop',
      'Pixel Transition',
      'Target Cursor',
      'Electric Border',
      'Sticker Peel',
      'Ribbons',
      'Glare Hover',
      'Magnet Lines',
      'Count Up',
      'Metallic Paint',
      'Click Spark',
      'Magnet',
      'Cubes',
      'Blob Cursor',
      'Meta Balls',
      'Image Trail',
      'Shape Blur',
      'Crosshair',
      'Star Border',
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Masonry',
      'Glass Surface',
      'Magic Bento',
      'Scroll Stack',
      'Profile Card',
      'Card Nav',
      'Pill Nav',
      'Dock',
      'Gooey Nav',
      'Pixel Card',
      'Carousel',
      'Spotlight Card',
      'Circular Gallery',
      'Flying Posters',
      'Folder',
      'Card Swap',
      'Infinite Scroll',
      'Tilted Card',
      'Glass Icons',
      'Decay Card',
      'Flowing Menu',
      'Elastic Slider',
      'Stack',
      'Chroma Grid',
      'Stepper',
      'Bounce Cards',
      'Counter',
      'Rolling Gallery'
    ]
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Aurora',
      'Beams',
      'Dark Veil',
      'Dither',
      'Dot Grid',
      'Hyperspeed',
      'Faulty Terminal',
      'Ripple Grid',
      'Silk',
      'Lightning',
      'Balatro',
      'Letter Glitch',
      'Particles',
      'Waves',
      'Squares',
      'Iridescence',
      'Threads',
      'Grid Motion',
      'Orb',
      'Ballpit',
      'Liquid Chrome',
      'Grid Distortion',
      'Galaxy',
      'Light Rays',
    ]
  }
];
