// Highlighted sidebar items
export const NEW = [
  'Antigravity',
  'Color Bends',
  'Floating Lines',
  'Ghost Cursor',
  'Grid Scan',
  'Laser Flow',
  'Light Pillar',
  'Liquid Ether',
  'Pixel Blast',
  'Pixel Snow',
];
export const UPDATED = ['Metallic Paint'];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Get Started',
    subcategories: [ 
      'Index', 
      'MCP'
    ],
  },
  {
    name: 'Text Animations',
    subcategories: [
      'Ascii Text',
      'Blur Text',
      'Circular Text',
      'Count Up',
      'Curved Loop',
      'Decrypted Text',
      'Falling Text',
      'Fuzzy Text',
      'Glitch Text',
      'Gradient Text',
      'Rotating Text',
      'Scroll Float',
      'Scroll Reveal',
      'Scroll Velocity',
      'Scramble Text',
      'Shiny Text',
      'Shuffle',
      'Split Text',
      'Text Cursor',
      'Text Pressure',
      'Text Trail',
      'Text Type',
      'True Focus',
      'Variable Proximity',
    ],
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Antigravity',
      'Blob Cursor',
      'Click Spark',
      'Crosshair',
      'Cubes',
      'Electric Border',
      'Fade Content',
      'Ghost Cursor',
      'Glare Hover',
      'Gradual Blur',
      'Image Trail',
      'Laser Flow',
      'Logo Loop',
      'Magnet',
      'Magnet Lines',
      'Metallic Paint',
      'Meta Balls',
      'Noise',
      'Pixel Trail',
      'Pixel Transition',
      'Ribbons',
      'Shape Blur',
      'Splash Cursor',
      'Star Border',
      'Sticker Peel',
      'Target Cursor',
    ],
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Bounce Cards',
      'Bubble Menu',
      'Card Nav',
      'Card Swap',
      'Carousel',
      'Chroma Grid',
      'Circular Gallery',
      'Counter',
      'Decay Card',
      'Dock',
      'Dome Gallery',
      'Elastic Slider',
      'Flowing Menu',
      'Flying Posters',
      'Folder',
      'Glass Icons',
      'Glass Surface',
      'Gooey Nav',
      'Infinite Menu',
      'Infinite Scroll',
      'Magic Bento',
      'Masonry',
      'Pill Nav',
      'Pixel Card',
      'Profile Card',
      'Rolling Gallery',
      'Scroll Stack',
      'Spotlight Card',
      'Stack',
      'Staggered Menu',
      'Stepper',
      'Tilted Card',
    ],
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Aurora',
      'Balatro',
      'Ballpit',
      'Beams',
      'Color Bends',
      'Dark Veil',
      'Dither',
      'Dot Grid',
      'Faulty Terminal',
      'Floating Lines',
      'Galaxy',
      'Gradient Blinds',
      'Grid Distortion',
      'Grid Motion',
      'Grid Scan',
      'Hyperspeed',
      'Iridescence',
      'Letter Glitch',
      'Light Pillar',
      'Light Rays',
      'Lightning',
      'Liquid Chrome',
      'Liquid Ether',
      'Orb',
      'Particles',
      'Pixel Blast',
      'Pixel Snow',
      'Plasma',
      'Prism',
      'Prismatic Burst',
      'Ripple Grid',
      'Silk',
      'Squares',
      'Threads',
      'Waves',
    ],
  },
];
