import type { Output } from 'jsrepo';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

export type ComponentDependenciesOutputOptions = {
  path: string;
};

export function pascalToKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

export function componentDependenciesOutput({ path }: ComponentDependenciesOutputOptions): Output {
  return {
    async output(buildResult, { cwd }) {
      const entries: [string, string[]][] = [];

      for (const item of buildResult.items) {
        const deps = item.dependencies?.map(d => d.name) ?? [];
        if (deps.length === 0) continue;
        entries.push([pascalToKebab(item.name), [...new Set(deps)]]);
      }

      entries.sort(([a], [b]) => a.localeCompare(b));

      const body = entries.map(([name, deps]) => `\t'${name}': [${deps.map(d => `'${d}'`).join(', ')}],`).join('\n');

      const contents = `// Generated by jsrepo build. Do not edit by hand.
export const COMPONENT_DEPENDENCIES: Record<string, string[]> = {
${body}
};

export function dependenciesForSlug(slug: string | undefined): string[] {
\treturn slug ? (COMPONENT_DEPENDENCIES[slug] ?? []) : [];
}
`;

      const absolute = resolve(cwd, path);
      await mkdir(dirname(absolute), { recursive: true });
      await writeFile(absolute, contents, 'utf8');
    },
    async clean({ cwd }) {
      await rm(resolve(cwd, path), { force: true });
    }
  };
}
